<?php
$questions = array(
    0 => ["Les dinausores existent-ils encore ?" , "Oui"],
    1 => ["Quel type d'acides sont présents dans les protéines ?" , "Aminés"],
    2 => ["Combien de frères a Grincheux ?" , "6"],
    3 => ["Qui est le gardien de but dans Olive et Tom ?" , "Tom"],
    4 => ["Quelle est la première couleur de Gandalf ?" , "Gris"],
    5 => ["Si vous n'êtes pas sorcier, vous êtes un ..." , "Moldu"],
    6 => ["Qui est le shérif de l'espace ?" , "XOR"],
    7 => ["Un escargot est dans un puits de 10 mètres. Il monte 3 mètres chaque jour et descend 2 mètres chaque nuit. En combien de jours sera-t-il rendu en haut ?" , "8"],
    8 => ["Si nous ne sommes pas le lendemain de lundi ou le jour avant jeudi, que demain n'est pas dimanche, que ce n'était pas dimanche hier et que le jour d'après-demain n'est pas samedi, et que le jour avant hier n'était pas mercredi, quel jour sommes-nous ?" , "Dimanche"],
    9 => ["Un artisan doit réaliser 100 plaques de rue numérotées de 1 a 100. Combien de fois devra t-il écrire le chiffre 9" , "20"],
    10 => ["Combien de couleurs faut-il pour créer du vert" , "2"],
    11 => ["Court Forest, ..." , "court"],
    12 => ["Ca dépend, ça ..." , "dépasse"],
    13 => ["Comment s'appelle le fils ainé de Son Goku" , "Gohan"],
    14 => ["Mon premier se balade sur la tête des enfants. Mon deuxième est le contraire féminin de « moche ». Quand on ouvre mon tout, on la referme rapidement." , "Poubelle"],
    15 => ["Comment se prénommait la soeur, sculptrice, de Paul Claudel ?" , "Camille"],
    16 => ["De quel pays Tirana est-elle la capitale ? " , "Albanie"],
    17 => ["Quel est l'impératif du verbe peindre à la 2e personne du pluriel ?" , "Peignez"],
);